backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "data"
    extension: "json"
    format: "json"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Product ID", name: "id", widget: "number"}
      - {label: "Product Name", name: "name", widget: "string"}
      - {label: "Price (₦)", name: "price", widget: "number"}
      - {label: "Stock Quantity", name: "stock", widget: "number", default: 5}
      - {label: "Product Image", name: "image", widget: "image"}